// packages/notification-center/src/components/NotificationCenterComponent.tsx
import React from 'react';
import ReactDOM from 'react-dom';

import { IMessage, MessageActionStatusEnum, ButtonTypeEnum, IOrganizationEntity } from '@novu/shared';
import reactToWebComponent from 'react-to-webcomponent';

import { INovuProviderProps, NovuProvider } from './novu-provider';
import { useNotifications } from '../hooks';
import { PopoverNotificationCenter } from './popover-notification-center';
import { INotificationBellProps, NotificationBell } from './notification-bell';

export interface NotificationCenterComponentProps {
  stores?: INovuProviderProps['stores'];
  backendUrl?: INovuProviderProps['backendUrl'];
  socketUrl?: INovuProviderProps['socketUrl'];
  subscriberId?: INovuProviderProps['subscriberId'];
  applicationIdentifier: INovuProviderProps['applicationIdentifier'];
  onLoad?: INovuProviderProps['onLoad'];
  subscriberHash?: INovuProviderProps['subscriberHash'];
  i18n?: INovuProviderProps['i18n'];
  colorScheme?: 'light' | 'dark';
  // TODO: remove this prop
  asd?: any;
}

/*
 * This array represents the public API of the web component.
 * All the props defined in the NotificationCenterComponentProps should be added here.
 */
export const NOTIFICATION_CENTER_PROPS = [
  'stores',
  'backendUrl',
  'socketUrl',
  'subscriberId',
  'applicationIdentifier',
  'onLoad',
  'subscriberHash',
  'i18n',
  'colorScheme',
  // TODO: remove this prop
  'asd',
];

export const NotificationCenterComponent = ({
  backendUrl,
  socketUrl,
  subscriberId,
  applicationIdentifier,
  colorScheme = 'dark',
  asd,
}: NotificationCenterComponentProps) => {
  console.log({ backendUrl, socketUrl, subscriberId, applicationIdentifier, asd });

  return (
    <NovuProvider
      backendUrl={backendUrl}
      socketUrl={socketUrl}
      subscriberId={subscriberId}
      applicationIdentifier={applicationIdentifier}
    >
      <PopoverWrapper colorScheme={colorScheme} />
    </NovuProvider>
  );
};

function PopoverWrapper({ colorScheme }: Pick<NotificationCenterComponentProps, 'colorScheme'>) {
  const { updateAction, markAsSeen } = useNotifications();

  function handlerOnNotificationClick(message: IMessage) {
    if (message?.cta?.data?.url) {
      markAsSeen();
      window.location.href = message.cta.data.url;
    }
  }

  async function handlerOnActionClick(_: string, type: ButtonTypeEnum, message: IMessage) {
    await updateAction(message._id, type, MessageActionStatusEnum.DONE);
  }

  return (
    <PopoverNotificationCenter
      colorScheme={colorScheme}
      onNotificationClick={handlerOnNotificationClick}
      onActionClick={handlerOnActionClick}
    >
      {({ unseenCount }) => {
        return <NotificationBell colorScheme={colorScheme} unseenCount={unseenCount} />;
      }}
    </PopoverNotificationCenter>
  );
}

export const NotificationCenterWebComponent = reactToWebComponent(NotificationCenterComponent, React, ReactDOM, {
  props: NOTIFICATION_CENTER_PROPS,
});

customElements.define('notification-center-component', NotificationCenterWebComponent);

// packages/notification-center/src/components/notification-center-web-component/notification-center-component.tsx
import React, { FunctionComponent } from 'react';
import { IMessage, MessageActionStatusEnum, ButtonTypeEnum } from '@novu/shared';

import { NovuProvider } from '../novu-provider';
import { PopoverNotificationCenter } from '../popover-notification-center';
import { NotificationBell } from '../notification-bell';
import { reactToWebComponent } from '../../utils';
import type { NotificationCenterComponentProps, PopoverWrapperProps } from './notification-center-component.types';
import { useUpdateAction } from '../../hooks';

/*
 * This array represents the public API of the web component.
 * All the props defined in the NotificationCenterComponentProps should be added here.
 */
export const NOTIFICATION_CENTER_PROPS = [
  'backendUrl',
  'socketUrl',
  'subscriberId',
  'applicationIdentifier',
  'subscriberHash',
  'stores',
  'tabs',
  'showUserPreferences',
  'popover',
  'theme',
  'styles',
  'colorScheme',
  'i18n',
  'onLoad',
  'sessionLoaded',
  'onNotificationClick',
  'notificationClicked',
  'onUnseenCountChanged',
  'unseenCountChanged',
  'onActionClick',
  'actionClicked',
  'onTabClick',
  'tabClicked',
];

export const NotificationCenterComponent: FunctionComponent<NotificationCenterComponentProps> = ({
  backendUrl,
  socketUrl,
  subscriberId,
  applicationIdentifier,
  subscriberHash,
  stores,
  tabs,
  showUserPreferences,
  popover,
  theme,
  styles,
  colorScheme = 'dark',
  i18n,
  sessionLoaded,
  onLoad = sessionLoaded,
  notificationClicked,
  onNotificationClick = notificationClicked,
  unseenCountChanged,
  onUnseenCountChanged = unseenCountChanged,
  actionClicked,
  onActionClick = actionClicked,
  tabClicked,
  onTabClick = tabClicked,
}) => {
  return (
    <NovuProvider
      onLoad={onLoad}
      stores={stores}
      backendUrl={backendUrl}
      socketUrl={socketUrl}
      subscriberId={subscriberId}
      applicationIdentifier={applicationIdentifier}
      subscriberHash={subscriberHash}
      styles={styles}
      i18n={i18n}
    >
      <PopoverWrapper
        onNotificationClick={onNotificationClick}
        onUnseenCountChanged={onUnseenCountChanged}
        onActionClick={onActionClick}
        onTabClick={onTabClick}
        colorScheme={colorScheme}
        theme={theme}
        tabs={tabs}
        showUserPreferences={showUserPreferences}
        popover={popover}
      />
    </NovuProvider>
  );
};

function PopoverWrapper({
  onNotificationClick,
  onUnseenCountChanged,
  onActionClick,
  onTabClick,
  colorScheme = 'dark',
  theme,
  tabs,
  showUserPreferences,
  popover,
  unseenBadgeColor,
  unseenBadgeBackgroundColor,
}: PopoverWrapperProps) {
  const { updateAction } = useUpdateAction();

  function handlerOnActionClick(templateIdentifier: string, type: ButtonTypeEnum, message: IMessage) {
    updateAction({ messageId: message._id, actionButtonType: type, status: MessageActionStatusEnum.DONE });
    onActionClick?.(templateIdentifier, type, message);
  }

  return (
    <PopoverNotificationCenter
      onNotificationClick={onNotificationClick}
      onUnseenCountChanged={onUnseenCountChanged}
      onActionClick={handlerOnActionClick}
      onTabClick={onTabClick}
      colorScheme={colorScheme}
      theme={theme}
      tabs={tabs}
      showUserPreferences={showUserPreferences}
      offset={popover?.offset}
      position={popover?.position}
    >
      {({ unseenCount }) => (
        <NotificationBell
          colorScheme={colorScheme}
          unseenCount={unseenCount}
          unseenBadgeColor={unseenBadgeColor}
          unseenBadgeBackgroundColor={unseenBadgeBackgroundColor}
        />
      )}
    </PopoverNotificationCenter>
  );
}

export const NotificationCenterWebComponent = reactToWebComponent(NotificationCenterComponent, {
  props: NOTIFICATION_CENTER_PROPS,
});
