// packages/notification-center/src/components/NotificationCenterComponent.tsx
import React from 'react';
import ReactDOM from 'react-dom';

import { IMessage, MessageActionStatusEnum, ButtonTypeEnum, IOrganizationEntity } from '@novu/shared';
import reactToWebComponent from 'react-to-webcomponent';

import { INovuProviderProps, NovuProvider } from './novu-provider';
import { useNotifications } from '../hooks';
import { PopoverNotificationCenter } from './popover-notification-center';
import { INotificationBellProps, NotificationBell } from './notification-bell';

export interface NotificationCenterComponentProps {
  stores?: INovuProviderProps['stores'];
  backendUrl?: INovuProviderProps['backendUrl'];
  socketUrl?: INovuProviderProps['socketUrl'];
  subscriberId?: INovuProviderProps['subscriberId'];
  applicationIdentifier: INovuProviderProps['applicationIdentifier'];
  onLoad?: INovuProviderProps['onLoad'];
  subscriberHash?: INovuProviderProps['subscriberHash'];
  i18n?: INovuProviderProps['i18n'];
  colorScheme?: 'light' | 'dark';
  // TODO: remove this prop
  asd?: any;
}

/*
 * This array represents the public API of the web component.
 * All the props defined in the NotificationCenterComponentProps should be added here.
 */
export const NOTIFICATION_CENTER_PROPS = [
  'stores',
  'backendUrl',
  'socketUrl',
  'subscriberId',
  'applicationIdentifier',
  'onLoad',
  'subscriberHash',
  'i18n',
  'colorScheme',
  // TODO: remove this prop
  'asd',
];

export const NotificationCenterComponent = ({
  backendUrl,
  socketUrl,
  subscriberId,
  applicationIdentifier,
  colorScheme = 'dark',
  asd,
}: NotificationCenterComponentProps) => {
  console.log({ backendUrl, socketUrl, subscriberId, applicationIdentifier, asd });

  return (
    <NovuProvider
      backendUrl={backendUrl}
      socketUrl={socketUrl}
      subscriberId={subscriberId}
      applicationIdentifier={applicationIdentifier}
    >
      <PopoverWrapper colorScheme={colorScheme} />
    </NovuProvider>
  );
};

function PopoverWrapper({ colorScheme }: Pick<NotificationCenterComponentProps, 'colorScheme'>) {
  const { updateAction, markAsSeen } = useNotifications();

  function handlerOnNotificationClick(message: IMessage) {
    if (message?.cta?.data?.url) {
      markAsSeen();
      window.location.href = message.cta.data.url;
    }
  }

  async function handlerOnActionClick(_: string, type: ButtonTypeEnum, message: IMessage) {
    await updateAction(message._id, type, MessageActionStatusEnum.DONE);
  }

  return (
    <PopoverNotificationCenter
      colorScheme={colorScheme}
      onNotificationClick={handlerOnNotificationClick}
      onActionClick={handlerOnActionClick}
    >
      {({ unseenCount }) => {
        return <NotificationBell colorScheme={colorScheme} unseenCount={unseenCount} />;
      }}
    </PopoverNotificationCenter>
  );
}

export const NotificationCenterWebComponent = reactToWebComponent(NotificationCenterComponent, React, ReactDOM, {
  props: NOTIFICATION_CENTER_PROPS,
});

customElements.define('notification-center-component', NotificationCenterWebComponent);

// packages/notification-center/src/components/notification-center-component.tsx
import React, { FunctionComponent } from 'react';
import { IMessage, MessageActionStatusEnum, ButtonTypeEnum } from '@novu/shared';

import { INovuProviderProps, NovuProvider } from './novu-provider';
import { IPopoverNotificationCenterProps, PopoverNotificationCenter } from './popover-notification-center';
import { NotificationBell } from './notification-bell';
import { useNotifications } from '../hooks';
import { reactToWebComponent } from '../utils';
import { ColorScheme } from '../shared/config/colors';

type NovuProviderProps = Pick<
  INovuProviderProps,
  | 'onLoad'
  | 'stores'
  | 'backendUrl'
  | 'socketUrl'
  | 'subscriberId'
  | 'applicationIdentifier'
  | 'subscriberHash'
  | 'i18n'
> & {
  // Angular props
  sessionLoaded?: INovuProviderProps['onLoad'];
};
type PopoverProps = Pick<
  IPopoverNotificationCenterProps,
  | 'onUrlChange'
  | 'onUnseenCountChanged'
  | 'onActionClick'
  | 'onTabClick'
  | 'theme'
  | 'tabs'
  | 'showUserPreferences'
  | 'offset'
  | 'position'
> & {
  onNotificationClick?: IPopoverNotificationCenterProps['onNotificationClick'];
  colorScheme?: ColorScheme;
  // Angular props
  urlChanged?: IPopoverNotificationCenterProps['onUrlChange'];
  notificationClicked?: IPopoverNotificationCenterProps['onNotificationClick'];
  unseenCountChanged?: IPopoverNotificationCenterProps['onUnseenCountChanged'];
  actionClicked?: IPopoverNotificationCenterProps['onActionClick'];
  tabClicked?: IPopoverNotificationCenterProps['onTabClick'];
};
type BellProps = { unseenBadgeColor?: string; unseenBadgeBackgroundColor?: string };

export type NotificationCenterComponentProps = NovuProviderProps & PopoverProps & BellProps;

type PopoverWrapperProps = PopoverProps & BellProps;

/*
 * This array represents the public API of the web component.
 * All the props defined in the NotificationCenterComponentProps should be added here.
 */
export const NOTIFICATION_CENTER_PROPS = [
  // NovuProvider props
  'onLoad',
  'sessionLoaded',
  'stores',
  'backendUrl',
  'socketUrl',
  'subscriberId',
  'applicationIdentifier',
  'subscriberHash',
  'i18n',
  // PopoverNotificationCenter props
  'onUrlChange',
  'onNotificationClick',
  'onUnseenCountChanged',
  'onActionClick',
  'onTabClick',
  'colorScheme',
  'theme',
  'tabs',
  'showUserPreferences',
  'offset',
  'position',
  // NotificationBell props
  'unseenBadgeColor',
  'unseenBadgeBackgroundColor',
];

export const NotificationCenterComponent: FunctionComponent<NotificationCenterComponentProps> = ({
  // NovuProvider props
  sessionLoaded,
  onLoad = sessionLoaded,
  stores,
  backendUrl,
  socketUrl,
  subscriberId,
  applicationIdentifier,
  subscriberHash,
  i18n,
  // PopoverNotificationCenter props
  urlChanged,
  onUrlChange = urlChanged,
  notificationClicked,
  onNotificationClick = notificationClicked,
  unseenCountChanged,
  onUnseenCountChanged = unseenCountChanged,
  actionClicked,
  onActionClick = actionClicked,
  tabClicked,
  onTabClick = tabClicked,
  colorScheme = 'dark',
  theme,
  tabs,
  showUserPreferences,
  offset,
  position,
  // NotificationBell props
  unseenBadgeColor,
  unseenBadgeBackgroundColor,
}) => {
  return (
    <NovuProvider
      onLoad={onLoad}
      stores={stores}
      backendUrl={backendUrl}
      socketUrl={socketUrl}
      subscriberId={subscriberId}
      applicationIdentifier={applicationIdentifier}
      subscriberHash={subscriberHash}
      i18n={i18n}
    >
      <PopoverWrapper
        onUrlChange={onUrlChange}
        onNotificationClick={onNotificationClick}
        onUnseenCountChanged={onUnseenCountChanged}
        onActionClick={onActionClick}
        onTabClick={onTabClick}
        colorScheme={colorScheme}
        theme={theme}
        tabs={tabs}
        showUserPreferences={showUserPreferences}
        offset={offset}
        position={position}
        unseenBadgeColor={unseenBadgeColor}
        unseenBadgeBackgroundColor={unseenBadgeBackgroundColor}
      />
    </NovuProvider>
  );
};

function PopoverWrapper({
  onUrlChange,
  onNotificationClick,
  onUnseenCountChanged,
  onActionClick,
  onTabClick,
  colorScheme = 'dark',
  theme,
  tabs,
  showUserPreferences,
  offset,
  position,
  unseenBadgeColor,
  unseenBadgeBackgroundColor,
}: PopoverWrapperProps) {
  const { updateAction, markAsSeen } = useNotifications();

  function handlerOnNotificationClick(message: IMessage) {
    if (message?.cta?.data?.url) {
      markAsSeen();
    }
    onNotificationClick?.(message);
  }

  async function handlerOnActionClick(templateIdentifier: string, type: ButtonTypeEnum, message: IMessage) {
    await updateAction(message._id, type, MessageActionStatusEnum.DONE);
    onActionClick?.(templateIdentifier, type, message);
  }

  return (
    <PopoverNotificationCenter
      onUrlChange={onUrlChange}
      onNotificationClick={handlerOnNotificationClick}
      onUnseenCountChanged={onUnseenCountChanged}
      onActionClick={handlerOnActionClick}
      onTabClick={onTabClick}
      colorScheme={colorScheme}
      theme={theme}
      tabs={tabs}
      showUserPreferences={showUserPreferences}
      offset={offset}
      position={position}
    >
      {({ unseenCount }) => (
        <NotificationBell
          colorScheme={colorScheme}
          unseenCount={unseenCount}
          unseenBadgeColor={unseenBadgeColor}
          unseenBadgeBackgroundColor={unseenBadgeBackgroundColor}
        />
      )}
    </PopoverNotificationCenter>
  );
}

export const NotificationCenterWebComponent = reactToWebComponent(NotificationCenterComponent, {
  props: NOTIFICATION_CENTER_PROPS,
});
