// packages/notification-center-core/src/components/novu-provider/novu-provider.tsx
import { Component, State, Prop, Watch, h } from '@stencil/core';
import { QueryObserverResult, QueryObserverOptions } from '@tanstack/query-core';
import { IOrganizationEntity, IMessage, ISubscriberJwt } from '@novu/shared';
import { ApiService } from '@novu/client';

import { ColorScheme, IStore, Session } from '../../types';
import { I18NLanguage, ITranslationEntry } from '../../i18n/lang';
import queryClient from '../../utils/queryClient';
import { initialNovuContext, INovuContext, NovuContext } from './novu-context';
import { AuthContext, IAuthContext } from './auth-context';

const FIVE_MINUTES = 5 * 60 * 1000;

function isBrowser() {
  return typeof window !== 'undefined';
}

function getToken(): string {
  if (isBrowser()) {
    return localStorage.getItem('widget_user_auth_token') as string;
  }

  return null;
}

@Component({
  tag: 'novu-provider',
})
export class NovuProvider {
  @Prop() stores: IStore[] = [{ storeId: 'default_store' }];
  @Prop() backendUrl?: string;
  @Prop() subscriberId?: string;
  @Prop() applicationIdentifier: string;
  @Prop() colorScheme?: ColorScheme;
  @Prop() socketUrl?: string;
  @Prop() subscriberHash?: string;
  @Prop() i18n?: I18NLanguage | ITranslationEntry;

  @State() token = getToken();
  @State() activeStore: IStore = this.stores[0];
  @State() user: ISubscriberJwt | null = null;
  @State() authContextValue: IAuthContext;
  @State() novuContextValue: INovuContext = initialNovuContext;
  @State() fetchOrgAndNotifications = false;

  private unsunscribeList: Array<() => void> = [];
  private api: ApiService;
  private sessionQueryOptions: QueryObserverOptions<Session, any> = {
    queryKey: ['session'],
    refetchOnWindowFocus: false,
    cacheTime: Infinity,
    staleTime: Infinity,
  };
  private organizationQueryOptions: QueryObserverOptions<IOrganizationEntity, any> = {
    enabled: false,
    queryKey: ['organization'],
    refetchOnWindowFocus: false,
    cacheTime: Infinity,
    staleTime: Infinity,
  };
  private notificationsQueryOptions: QueryObserverOptions<IMessage[], any> = {
    enabled: false,
    queryKey: ['notifications', this.activeStore.storeId, 0],
    refetchOnWindowFocus: false,
    cacheTime: FIVE_MINUTES,
    staleTime: FIVE_MINUTES,
  };

  connectedCallback() {
    const backendUrl = this.backendUrl ?? 'https://api.novu.co';
    const socketUrl = this.socketUrl ?? 'https://ws.novu.co';
    this.api = new ApiService(backendUrl);
    this.applyToken(this.token);
    this.novuContextValue = {
      ...this.novuContextValue,
      backendUrl,
      socketUrl,
      api: this.api,
      stores: this.stores,
      activeStore: this.activeStore,
      setActiveStore: this.setActiveStore,
    };
    this.authContextValue = {
      token: this.token,
      user: this.user,
      isLoggedIn: !!this.token,
    };
    this.resizeIframe();
  }

  disconnectedCallback() {
    this.unsunscribeList.forEach((unsubscribe) => unsubscribe());
  }

  @Watch('applicationIdentifier')
  watchApplicationIdentifierChange() {
    this.refetchAllSession();
  }

  @Watch('subscriberId')
  watchSubscriberIdChange() {
    this.refetchAllSession();
  }

  @Watch('subscriberHash')
  watchSubscriberHashChange() {
    this.refetchAllSession();
  }

  @Watch('stores')
  watchStoresChange(stores: IStore[]) {
    this.refetchAllSession();
    this.activeStore = this.stores[0];
    this.novuContextValue = {
      ...this.novuContextValue,
      stores,
      activeStore: this.activeStore,
    };
  }

  @Watch('activeStore')
  watchActiveStoreChange(newActiveStore: IStore) {
    this.notificationsQueryOptions = {
      ...this.notificationsQueryOptions,
      queryKey: ['notifications', newActiveStore.storeId, 0],
    };
  }

  private fetchSession = () =>
    this.api.initializeSession(this.applicationIdentifier, this.subscriberId, this.subscriberHash);

  private fetchOrganization = () => this.api.getOrganization();

  private fetchNotifications = () => {
    return this.api.getNotificationsList(0, this.activeStore.query);
  };

  private fetchSessionSuccess = (session: Session) => {
    this.fetchOrgAndNotifications = true;

    this.applyToken(session.token);
    this.setUser(session.profile);
  };

  private refetchAllSession() {
    this.fetchOrgAndNotifications = false;

    queryClient.refetchQueries({ queryKey: ['session'] });
    queryClient.removeQueries({ queryKey: ['organization'] });
    queryClient.removeQueries({ queryKey: ['notifications'], exact: false });
  }

  private applyToken = (newToken: string | null) => {
    if (newToken) {
      this.token = newToken;
      isBrowser() && localStorage.setItem('widget_user_auth_token', newToken);
      this.api.setAuthorizationToken(newToken);
    } else {
      this.token = null;
      isBrowser() && localStorage.removeItem('widget_user_auth_token');
      this.api.disposeAuthorizationToken();
    }
  };

  private setActiveStore = (storeId: string) => {
    const store = this.stores.find((el) => el.storeId === storeId);
    if (store) {
      this.activeStore = store;
      this.novuContextValue = {
        ...this.novuContextValue,
        activeStore: store,
      };
    }
  };

  private setUser(user: ISubscriberJwt | null) {
    this.authContextValue = {
      ...this.authContextValue,
      user,
    };
  }

  private resizeIframe() {
    if ('parentIFrame' in window) {
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      (window as any).parentIFrame.autoResize(true);
    }
  }

  private listenSessionChange = ({ isLoading, data }: QueryObserverResult<Session, any>) => {
    this.novuContextValue = {
      ...this.novuContextValue,
      session: { isLoading, data },
    };
  };

  private listenOrganizationChange = ({ isLoading, data }: QueryObserverResult<IOrganizationEntity, any>) => {
    this.novuContextValue = {
      ...this.novuContextValue,
      organization: { isLoading, data },
    };
  };

  private listenNotificationsChange = ({ isLoading, data }: QueryObserverResult<IMessage[], any>) => {
    this.novuContextValue = {
      ...this.novuContextValue,
      notifications: { isLoading, data },
    };
  };

  render() {
    return (
      <stencil-query
        options={{
          ...this.sessionQueryOptions,
          queryFn: this.fetchSession,
          onSuccess: this.fetchSessionSuccess,
        }}
        listen={this.listenSessionChange}
      >
        <stencil-query
          options={{
            ...this.organizationQueryOptions,
            enabled: this.fetchOrgAndNotifications,
            queryFn: this.fetchOrganization,
          }}
          listen={this.listenOrganizationChange}
        >
          <stencil-query
            options={{
              ...this.notificationsQueryOptions,
              enabled: this.fetchOrgAndNotifications,
              queryFn: this.fetchNotifications,
            }}
            listen={this.listenNotificationsChange}
          >
            <NovuContext.Provider value={this.novuContextValue}>
              <AuthContext.Provider value={this.authContextValue}>
                <slot />
              </AuthContext.Provider>
            </NovuContext.Provider>
          </stencil-query>
        </stencil-query>
      </stencil-query>
    );
  }
}

// packages/notification-center/src/components/novu-provider/NovuProvider.tsx
import React, { ReactElement, useEffect, useState, useMemo, useCallback } from 'react';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { IOrganizationEntity } from '@novu/shared';
import { ApiService } from '@novu/client';

import type { I18NLanguage, ITranslationEntry } from '../../i18n/lang';
import { NotificationsProvider } from '../../store/notifications-provider.context';
import { NovuContext } from '../../store/novu-provider.context';
import { NovuI18NProvider } from '../../store/i18n.context';
import type { IStore, ISession, IFetchingStrategy } from '../../shared/interfaces';
import { INotificationCenterStyles, StylesProvider } from '../../store/styles';
import { applyToken } from '../../utils/token';
import { useSession } from '../../hooks/useSession';
import { useInitializeSocket } from '../../hooks/useInitializeSocket';
import { useFetchOrganization, useNovuContext } from '../../hooks';

const queryClient = new QueryClient({
  defaultOptions: {
    queries: {
      refetchOnMount: false,
      refetchOnWindowFocus: false,
    },
  },
});

const DEFAULT_FETCHING_STRATEGY: IFetchingStrategy = {
  fetchUnseenCount: true,
  fetchOrganization: true,
  fetchNotifications: false,
  fetchUserPreferences: false,
};

export interface INovuProviderProps {
  stores?: IStore[];
  children: React.ReactNode;
  backendUrl?: string;
  subscriberId?: string;
  applicationIdentifier: string;
  socketUrl?: string;
  onLoad?: (data: { organization: IOrganizationEntity }) => void;
  subscriberHash?: string;
  i18n?: I18NLanguage | ITranslationEntry;
  styles?: INotificationCenterStyles;
  initialFetchingStrategy?: Partial<IFetchingStrategy>;
}

export function NovuProvider({
  backendUrl: initialBackendUrl,
  socketUrl: initialSocketUrl,
  applicationIdentifier,
  subscriberId,
  subscriberHash,
  stores: initialStores,
  i18n,
  styles,
  initialFetchingStrategy = DEFAULT_FETCHING_STRATEGY,
  children,
  onLoad,
}: INovuProviderProps) {
  const backendUrl = initialBackendUrl ?? 'https://api.novu.co';
  const socketUrl = initialSocketUrl ?? 'https://ws.novu.co';
  const stores = initialStores ?? [{ storeId: 'default_store' }];
  const [fetchingStrategy, setFetchingStrategyState] = useState({
    ...DEFAULT_FETCHING_STRATEGY,
    ...initialFetchingStrategy,
  });

  const [isSessionInitialized, setSessionInitialized] = useState(false);

  const apiService = useMemo(() => {
    queryClient.clear();
    const service = new ApiService(backendUrl);
    applyToken({ apiService: service, appId: applicationIdentifier });

    return service;
  }, [backendUrl, applicationIdentifier]);

  const { socket, initializeSocket, disconnectSocket } = useInitializeSocket({ socketUrl });

  const onSuccessfulSession = useCallback(
    (newSession: ISession) => {
      applyToken({ apiService, token: newSession.token, appId: applicationIdentifier });
      initializeSocket(newSession);
      setSessionInitialized(true);
    },
    [apiService, setSessionInitialized, initializeSocket, applicationIdentifier]
  );

  const setFetchingStrategy = useCallback(
    (strategy: Partial<IFetchingStrategy>) => setFetchingStrategyState((old) => ({ ...old, ...strategy })),
    [setFetchingStrategyState]
  );

  const contextValue = useMemo(
    () => ({
      backendUrl,
      socketUrl,
      applicationIdentifier,
      subscriberId,
      subscriberHash,
      isSessionInitialized,
      apiService,
      socket,
      fetchingStrategy,
      setFetchingStrategy,
      onLoad,
    }),
    [
      backendUrl,
      socketUrl,
      applicationIdentifier,
      subscriberId,
      subscriberHash,
      isSessionInitialized,
      apiService,
      socket,
      fetchingStrategy,
      setFetchingStrategy,
      onLoad,
    ]
  );

  useEffect(() => disconnectSocket, [disconnectSocket]);

  return (
    <QueryClientProvider client={queryClient}>
      <NovuContext.Provider value={contextValue}>
        <SessionInitializer onSuccess={onSuccessfulSession}>
          <NotificationsProvider stores={stores}>
            <NovuI18NProvider i18n={i18n}>
              <StylesProvider styles={styles}>{children}</StylesProvider>
            </NovuI18NProvider>
          </NotificationsProvider>
        </SessionInitializer>
      </NovuContext.Provider>
    </QueryClientProvider>
  );
}

const SessionInitializer = ({
  children,
  onSuccess,
}: {
  children: ReactElement;
  onSuccess: (newSession: ISession) => void;
}) => {
  const { onLoad } = useNovuContext();

  useSession({ onSuccess });

  useFetchOrganization({
    onSuccess: (organization) => {
      onLoad?.({ organization });
    },
  });

  useEffect(() => {
    if ('parentIFrame' in window) {
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      (window as any).parentIFrame.autoResize(true);
    }
  }, []);

  return children;
};
