// packages/vue/src/components/InboxContent.vue
<script setup lang="ts">
import { useSlots, h } from "vue";
import Mounter from './Mounter.vue';  // Assuming Mounter is a Vue component
import { InboxPage, NotificationRenderer } from '@novu/js/ui';
import { useNovuUI } from '../context/NovuUIProviderContext';

interface Slots {
  notification?: (props: { notification: Parameters<NotificationRenderer>[1] }) => any;
}

interface Props {
  onNotificationClick?: (notification: any) => void;
  onPrimaryActionClick?: () => void;
  onSecondaryActionClick?: () => void;
  initialPage?: InboxPage;
  hideNav?: boolean;
}

const props = defineProps<Props>();
const slots = useSlots() as unknown as Slots; // Get access to the slot content

const novuUI = useNovuUI();

const mount = (element: HTMLElement, mountElement: (el: HTMLElement, mountedElement: any) => void) => novuUI.mountComponent({
  name: 'InboxContent',
  element,
  props: {
    renderNotification: (slots.notification ? (el: Parameters<NotificationRenderer>[0], notification: Parameters<NotificationRenderer>[1]) => {
      const slotContent = slots.notification?.({ notification });

      if (slotContent) {
        const vnode = slotContent.length > 1 ? h("div", {}, slotContent) : slotContent[0];
        mountElement(el, vnode);
      }
    } : undefined) as NotificationRenderer | undefined,
    onNotificationClick: props.onNotificationClick,
    onPrimaryActionClick: props.onPrimaryActionClick,
    onSecondaryActionClick: props.onSecondaryActionClick,
    initialPage: props.initialPage,
    hideNav: props.hideNav
  },
});
</script>

<template>
  <Mounter :mount="mount" />
</template>

// packages/react/src/components/InboxContent.tsx
import React from 'react';
import type { NotificationClickHandler, NotificationActionClickHandler, InboxPage } from '@novu/js/ui';
import { Mounter } from './Mounter';
import { NotificationsRenderer } from '../utils/types';
import { useRenderer } from '../context/RendererContext';
import { useNovuUI } from '../context/NovuUIContext';
import { withRenderer } from './Renderer';

export type InboxContentProps = {
  renderNotification?: NotificationsRenderer;
  onNotificationClick?: NotificationClickHandler;
  onPrimaryActionClick?: NotificationActionClickHandler;
  onSecondaryActionClick?: NotificationActionClickHandler;
  initialPage?: InboxPage;
  hideNav?: boolean;
};

const _InboxContent = React.memo((props: InboxContentProps) => {
  const {
    onNotificationClick,
    onPrimaryActionClick,
    renderNotification,
    onSecondaryActionClick,
    initialPage,
    hideNav,
  } = props;
  const { novuUI } = useNovuUI();
  const { mountElement } = useRenderer();

  const mount = React.useCallback(
    (element: HTMLElement) => {
      return novuUI.mountComponent({
        name: 'InboxContent',
        element,
        props: {
          renderNotification: renderNotification
            ? (el, notification) => mountElement(el, renderNotification(notification))
            : undefined,
          onNotificationClick,
          onPrimaryActionClick,
          onSecondaryActionClick,
          initialPage,
          hideNav,
        },
      });
    },
    [renderNotification, onNotificationClick, onPrimaryActionClick, onSecondaryActionClick]
  );

  return <Mounter mount={mount} />;
});

export const InboxContent = withRenderer(_InboxContent);
