// packages/vue/src/components/Preferences.vue
<script setup lang="ts">
import { useNovuUI } from '../context/NovuUIProviderContext';
import Mounter from './Mounter.vue';  // Assuming Mounter is a Vue component

// Initialize the context
const novuUI = useNovuUI();

// Mounting the component when the element is ready
const mount = (element: HTMLElement) => novuUI.mountComponent({
  name: 'Preferences',
  element,
});
</script>

<template>
  <Mounter :mount="mount" />
</template>

// packages/react/src/components/Preferences.tsx
import React from 'react';
import { useNovuUI } from '../context/NovuUIContext';
import { Mounter } from './Mounter';

export const Preferences = () => {
  const { novuUI } = useNovuUI();

  const mount = React.useCallback((element: HTMLElement) => {
    return novuUI.mountComponent({
      name: 'Preferences',
      element,
    });
  }, []);

  return <Mounter mount={mount} />;
};
